### ISSUE TITLE
import pycloudlib => ModuleNotFoundError: No module named 'pycloudlib.openstack'

### ISSUE THREAD

**Issue by paride** [canonical/pycloudlib#126]
Landing https://github.com/canonical/pycloudlib/pull/113 made pycloudlib fail to load. Can be reproduced in a venv (here using quiet commands for readability):
```
$ cd /tmp
$ git clone --quiet https://github.com/canonical/pycloudlib

$ python3 -m venv /tmp/pcl.venv
$ source /tmp/pcl.venv/bin/activate
$ which python3
/tmp/pcl.venv/bin/python3
$ which pip
/tmp/pcl.venv/bin/pip

$ pip --quiet install --upgrade pip
$ pip --quiet install ./pycloudlib

$ python3
Python 3.9.2 (default, Feb 20 2021, 11:05:08) 
[GCC 10.2.1 20210206] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycloudlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/pcl.venv/lib/python3.9/site-packages/pycloudlib/__init__.py", line 11, in <module>
    from pycloudlib.openstack.cloud import Openstack
ModuleNotFoundError: No module named 'pycloudlib.openstack'
```

**Comment by OddBloke** [comment]
Fixed in #127
