### ISSUE TITLE
recent deps changes breaking downstream consumers on Focal/python 3.8

### ISSUE THREAD

**Issue by a-dubs** [canonical/pycloudlib#422]
```
18:47:07 Traceback (most recent call last):
...
18:47:07   File "/var/lib/jenkins/slaves/jenkins-agent-focal-ps5-3/workspace/maint-ci-cloudware-cloud-test-framework-test/gitclone/test_framework/tests/package_install_with_reboot/__init__.py", line 1, in <module>
18:47:07     from test_framework.clouds.azure import Azure
18:47:07   File "/var/lib/jenkins/slaves/jenkins-agent-focal-ps5-3/workspace/maint-ci-cloudware-cloud-test-framework-test/gitclone/test_framework/clouds/azure.py", line 9, in <module>
18:47:07     import pycloudlib
18:47:07   File "/var/lib/jenkins/slaves/jenkins-agent-focal-ps5-3/workspace/maint-ci-cloudware-cloud-test-framework-test/gitclone/.tox/ctf-run/lib/python3.8/site-packages/pycloudlib/__init__.py", line 8, in <module>
18:47:07     from pycloudlib.gce.cloud import GCE
18:47:07   File "/var/lib/jenkins/slaves/jenkins-agent-focal-ps5-3/workspace/maint-ci-cloudware-cloud-test-framework-test/gitclone/.tox/ctf-run/lib/python3.8/site-packages/pycloudlib/gce/cloud.py", line 17, in <module>
...
18:47:07   File "/var/lib/jenkins/slaves/jenkins-agent-focal-ps5-3/workspace/maint-ci-cloudware-cloud-test-framework-test/gitclone/.tox/ctf-run/lib/python3.8/site-packages/google/api_core/gapic_v1/config.py", line 23, in <module>
18:47:07 ModuleNotFoundError: No module named 'grpc'
18:47:07 Error: No module named 'grpc'
18:47:07 
```
in pip resolver:
ERROR: google-cloud-compute 1.19.2 has requirement protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you'll have protobuf 3.19.6 which is incompatible.

**Comment by aciba90** [comment]
PR fixing this: https://github.com/canonical/pycloudlib/pull/421.
