### ISSUE TITLE
Can't create OCI instance with '.' in the tag.

### ISSUE THREAD

**Issue by uhryniuk** [canonical/pycloudlib#449]
When creating an instance with a '.' in the name, this causes the following exception:
```
pycloudlib.errors.InvalidTagNameError: Tag 'oke-1.29-1021-000216' failed the following rules: Must be alphanumeric and hyphens only
```

This behaviour is not mirrored in Oracle Cloud, as instances can be created with "." their name such as "some.instance.example".

---

```
Traceback (most recent call last):
  File "/snap/test/x378/bin/test", line 8, in <module>
    sys.exit(main())
  File "/snap/test/x378/lib/python3.8/site-packages/test_framework/main.py", line 300, in main
    cli(obj={})
  File "/snap/test/x378/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/snap/test/x378/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/snap/test/x378/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/snap/test/x378/lib/python3.8/site-packages/click/core.py", line 1665, in invoke
    super().invoke(ctx)
  File "/snap/test/x378/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/test/x378/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/snap/test/x378/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/snap/test/x378/lib/python3.8/site-packages/test_framework/clouds/oracle.py", line 407, in cli
    ctx.obj["cloud"] = OracleCloud(
  File "/snap/test/x378/lib/python3.8/site-packages/test_framework/clouds/oracle.py", line 292, in __init__
    self.client = pycloudlib.OCI(
  File "/snap/test/x378/lib/python3.8/site-packages/pycloudlib/oci/cloud.py", line 66, in __init__
    super().__init__(
  File "/snap/test/x378/lib/python3.8/site-packages/pycloudlib/cloud.py", line 67, in __init__
    self._validate_tag(self.tag)
  File "/snap/test/x378/lib/python3.8/site-packages/pycloudlib/cloud.py", line 311, in _validate_tag
    raise InvalidTagNameError(tag=tag, rules_failed=rules_failed)

```

**Comment by uhryniuk** [comment]
After some investigation, the only for naming an instance is *the name must be between 1 - 255 characters after stripping trailing whitespace.*

All special characters seem to be allowed too.
