### ISSUE TITLE
Launching xenial LXD VMs is broken

### ISSUE THREAD

**Issue by OddBloke** [canonical/pycloudlib#71]
It fails like this:

```pytb
['lxc', 'init', 'images:ubuntu/16.04/cloud', 'pycloudlib-vm-x', '--profile', 'pycloudlib-vm-xenial', '--config', 'user.user-data=#cloud-config\nssh_authorized_keys:\n    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDbQjB24CbrqmNap6xTv1Wcp9/4lOS7CUhcmeHFy/LmvgrS1KUBkhP85OYBcUT3A6mfkdsPYw7p7dCrVl3TT+48tSSNYgV5z40yoIT85M02VltYfpLyLtkqS6e5EHqg45pGZa+hnQXw9G5UzGwUAfeXyI9Tkv+pL/rLda5PxkORdGUiRAiO2ZUIVss7VsxltL3L4qtvsgmf02qi4GQLi4dKrjiUnLWu7FC6+HFHVAEP6yaRrnNYOlCINa37yQdW8+uzmjc5VQJBQKb6RKhugbkv5KU1wmeMhKxZ6sdeJj2WWsZPWCf6nKyzzg6rnCe13X2JN21RKNnniaY4C0dcEOYnHHYiizfc4nWaLewfysTcAK0kufR/XX7qM2NdechKQiYrqf7da0VMujx7IBOoC6AV4+YYNVyttxpWX9rlIAwhbVKr65FoYlgQPUS3iQrmuTyKuo+L2eYGc/IwztZCCiHCJ4MW1mdiVh2GzTPI3iekW905rCv6Iout2omyQmBpiH/K2FENcNJH6Waj7AFeWSy64XQi8uL+jofihwkzZTW957+bIGaQxwV9IYill7p7NE2IrFKzG53EkO48KS7ToibD6rKLQU1gDiWaSll1v68f8ds9KKS35sBmjrE+2KcUQxF7VB7dk9ptDafc5JW6sGUvDA+QSOeTqhIqC7X1X/CJOQ==\n', '--vm']
Traceback (most recent call last):
  File "examples/lxd.py", line 232, in <module>
    demo()
  File "examples/lxd.py", line 227, in demo
    launch_virtual_machine()
  File "examples/lxd.py", line 201, in launch_virtual_machine
    inst = lxd.launch(
  File "/home/daniel/dev/pycloudlib/pycloudlib/lxd/cloud.py", line 315, in launch
    instance = self.init(
  File "/home/daniel/dev/pycloudlib/pycloudlib/lxd/cloud.py", line 282, in init
    result = subp(cmd)
  File "/home/daniel/dev/pycloudlib/pycloudlib/util.py", line 200, in subp
    raise RuntimeError(errmsg)
RuntimeError: Failure (rc=1): Error: Failed to fetch https://uk.images.linuxcontainers.org:8443/1.0/images/ubuntu/16.04/cloud: 404 Not Found
```

(Should we be using `ubuntu/xenial/cloud` instead?)

**Comment by OddBloke** [comment]
This ended up being an incorrect definition of the `images` remote for me locally, still using the `lxd` protocol instead of `simplestreams`; it worked for unslashed image names, but not slashed names.
