### ISSUE TITLE
Cannot launch hirsute LXD VM instances

### ISSUE THREAD

**Issue by OddBloke** [canonical/pycloudlib#95]
When I attempt to do so, I see the following traceback:

```pytb
Traceback (most recent call last):
  File "/home/daniel/scratch/cloud-init/tests/integration_tests/clouds.py", line 285, in _perform_launch
    profile_list = launch_kwargs['profile_list']
KeyError: 'profile_list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/daniel/scratch/cloud-init/tests/integration_tests/conftest.py", line 142, in setup_image
    client = session_cloud.launch()
  File "/home/daniel/scratch/cloud-init/tests/integration_tests/clouds.py", line 165, in launch
    pycloudlib_instance = self._perform_launch(kwargs)
  File "/home/daniel/scratch/cloud-init/tests/integration_tests/clouds.py", line 287, in _perform_launch
    profile_list = self._get_or_set_profile_list(release)
  File "/home/daniel/scratch/cloud-init/tests/integration_tests/clouds.py", line 316, in _get_or_set_profile_list
    self._profile_list = self.cloud_instance.build_necessary_profiles(
  File "/home/daniel/dev/pycloudlib/pycloudlib/lxd/cloud.py", line 608, in build_necessary_profiles
    base_release = self._extract_release_from_image_id(release)
  File "/home/daniel/dev/pycloudlib/pycloudlib/lxd/cloud.py", line 596, in _extract_release_from_image_id
    return self._image_info(image_id)[0]["release"]
IndexError: list index out of range
```

**Comment by OddBloke** [comment]
This issue does not present on LXD container launches.
